name    'inkblot/dante'
version '0.0.1'
source  'git://github.com/inkblot/puppet-dante.git'
author  'inkblot'
license 'Apache 2.0'
summary 'Dante SOCKS server'
description 'A Puppet module to install and configure a simple SOCKS server using Dante'
project_page 'https://github.com/inkblot/puppet-dante'

dependency 'ripienaar/module_data', '>= 0.0.1'
